runtime: nodejs20

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  # Database configuration - Using Cloud SQL connection name for App Engine
  DB_HOST: "/cloudsql/cmsc-127-flashcards:asia-southeast1:cmsc127"
  DB_NAME: "CMSC127"
  DB_USER: "postgres"   
  DB_PASSWORD: "psql"

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Static file serving
handlers:
  - url: /js
    static_dir: js
  - url: /styles.css
    static_files: styles.css
    upload: styles.css
  - url: /.*
    script: auto
    secure: always 